---
title: "Project_1"
output:
  word_document: default
  pdf_document: default
  html_notebook: default
---
```{r}
library(tidyverse)
library(here)
library(ggplot2)
library(gganimate)
library(ggthemes)
library(readxl)
```


```{r}
bank_additional <- read_excel("bank-additional.xlsx")
epldata_final <- read_excel("epldata_final.xlsx")
```


```{r}
glimpse(epldata_final)
```



```{r}
glimpse(bank_additional)
```
```{r}
# Plot 1
ggplot(bank_additional,aes(age)) +
# Simple density plot
geom_density(aes(fill=factor(term_deposit)), alpha=0.6) +
# Change theme color of graph
theme(plot.background = element_rect(fill = "lightblue"),
# Adjust thickness of x and y axis lines
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
# Adjust font size of x and y label
      axis.text.x = element_text(color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
# Adjust Legend parameters
      legend.position = c(0.86, 0.85),                        
      legend.spacing.y = unit(0.1,"cm"),                    
      legend.background = element_rect(fill="Grey",size=1,
                                       linetype="solid",
                                       colour="black"),
      legend.title = element_text(face = "bold"),
# Remove Grid Lines
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank()) +
# Label graph(title,subtitle) and its axis
labs(title="Analysis of Bank Telemarketing",                
     subtitle="Density of Age Group opting for Term Deposit",
     x = "Age",y = "Density",fill = 'Term Deposit taken?')
```
```{r}
# Plot 2
ggplot(epldata_final, aes(x = position)) +
# Simple histogram with fill and border line
geom_histogram(stat="count",fill = "tomato2",
               color = 'black',size = 1) +
# Changing Plot theme parameters
theme(plot.background = element_rect(fill = "lightblue"),           
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
      axis.text.x = element_text(color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
      legend.background = element_rect(fill="Grey",size=1,
                                       linetype="solid",
                                       colour="black"),
      legend.title = element_text(face = "bold"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank()) +
# Label graph(title,subtitle) and its axis
labs(title = "Analysis of English Premier League(EPL)",
     subtitle = "Distribution of Players by Position",
     fill = 'Region',x = "Position on Field",
     y = "Players' Count")
```
```{r}
# Plot 3
ggplot(bank_additional, aes(x = age,y = job)) +
# Simple scatter plot distributed by color as category
geom_point(bank_additional,mapping = aes(color = housing)) +
# Change theme parameters
theme(plot.background = element_rect(fill = "lightblue"),
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
      axis.text.x = element_text(color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
      legend.position = "top",
      legend.background = element_rect(fill="Grey",size=1,
                                       linetype="solid",colour="black"),
      legend.title = element_text(face = "bold")) +
# Label graph(title,subtitle) and its axis
labs(title = "Analysis of Bank Telemarketing",
     subtitle = 'Age VS Job type',
     color = 'Housing Loan',x = "Age",y = "Job type")
```
```{r}
# Plot 4
ggplot(epldata_final, aes(x = club,fill = region_name)) +
# Simple histogram with fill and border line
geom_histogram(stat="count",color = "black")  +
#Break sequence on y axis to make it more frequent
scale_y_continuous(breaks=seq(0,30,5)) +
# Change theme parameters
theme(plot.background = element_rect(fill = "lightblue"),
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
      axis.text.x = element_text(angle=90,vjust=0.30,hjust=1,color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
      legend.background = element_rect(fill="Grey",size=1,linetype="solid",colour="black"),
      legend.title = element_text(face = "bold"),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank()) +
# Label graph(title,subtitle) and its axis
labs(title = "Analysis of English Premier League(EPL)",
     subtitle = "Players' distribution across Club and Region",
     fill = 'Region',x = "Club",y = "Players' Count")
```
```{r}
#Plot 5
ggplot(bank_additional) +
# A simple scatter plot about to go faceting
geom_point(mapping = aes(x = campaign, y = month, color = emp.var.rate)) +
# Adding a facet grid with 2 variables
facet_grid(contact ~ day_of_week,scales = 'free')  +
# Changing theme parameters
theme(plot.background = element_rect(fill = "Skyblue"),
      strip.background = element_rect(fill="royalblue"),
      strip.text.x = element_text(colour = "black", face = "bold"),
      strip.text.y = element_text(colour = "black", face = "bold"),
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
      axis.text.x = element_text(color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
      axis.title.x.top = element_text(color="black",face="bold"),
      axis.title.y.right = element_text(color="black",face="bold"),
      axis.text.x.top = element_text(color="black",face="bold"),
      axis.text.y.right = element_text(color="black",face="bold"),
      legend.background = element_rect(fill="Grey",size=1,
                                       linetype="solid",colour="black"),
      legend.title = element_text(face = "bold")) +
# Label graph(title,subtitle) and its axis
labs(title="Analysis of Bank Telemarketing",
     subtitle="Campaign Vs Month",color = 'Emp Variation %',
     x = "Calls made during Campaign",y = "Month")
```

```{r}
# Plot 6
va <- ggplot(epldata_final,aes(fpl_value, market_value,
                               size = fpl_points,color = region_name)) +
# Adding scatter plot with single facet
geom_point(alpha = 0.5, show.legend = TRUE) +
facet_wrap(~region_name) +
# Transition through distinct states in time
transition_time(fpl_points) +
# The default easing function for aesthetics
ease_aes('linear') +
# Changing theme parameters
theme(plot.background = element_rect(fill = "royalblue1"),
      strip.background = element_rect(fill="turquoise"),
      strip.text.x = element_text(colour = "black", face = "bold"),
      strip.text.y = element_text(colour = "black", face = "bold"),
      axis.line = element_line(size = 1, colour = "black"),
      axis.title.x = element_text(color="black",face="bold"),
      axis.title.y = element_text(color="black",face="bold"),
      axis.text.x = element_text(color="black",face="bold"),
      axis.text.y = element_text(color="black",face="bold"),
      legend.background = element_rect(fill="skyblue1",size=1,
                                       linetype="solid",colour="black"),
      legend.title = element_text(face = "bold")) +
# Label graph(title,subtitle) and its axis
labs(title = "Football Premier League Points: {frame_time}",
     subtitle = "Relationship between Market Value and FPL Value",
     fill = 'Region',x = "FPL Value",y = "Market Value")
# Call animate function with 1 frame per second 
animate(va, fps = 1)
```

